### ISSUE TITLE
Can't solve math problems.

### ISSUE THREAD

**Issue by Sh-wayz** [thunder-red-star/villager-bot-auto-miner#1]
![image](https://user-images.githubusercontent.com/67710582/115893247-f7055880-a425-11eb-9085-20618f15371f.png)
![image](https://user-images.githubusercontent.com/67710582/115893301-05537480-a426-11eb-800f-0bc2a6d5eb83.png)
Might want to look into that.

**Comment by thunder-red-star** [comment]
I'll look into that, thanks

**Comment by thunder-red-star** [comment]
It'll be hard to debug since I'm botbanned but I'll find a solution 😉

**Comment by Iapetus-11** [comment]
~~an alt~~

**Comment by thunder-red-star** [comment]
Unfortunately, I'm gonna guess that you edited the code under Iapetus11's command since I tested the mechanism and it worked fine (on my bot, on a similar embed). 

If not, please redownload the code and make sure it has `.join("")` at the end of the question logger.

I had a look at your profile and I can see that you're related to Iapetus11 in many ways...

To Iapetus11: Do you really think I'm gonna sabotage my own code so you can have a reason to close that issue? 

# Very funny guys.

**Comment by Iapetus-11** [comment]
lmfao he figured it out guys RETREAT

**Comment by thunder-red-star** [comment]
Also to Iapetus11: Stop using bot clients you could get your tokens revoked.

**Comment by Iapetus-11** [comment]
?

**Comment by thunder-red-star** [comment]
I highly doubt you could find 1 server / 20k and invite yourself to it just from a 1.5 GB RAM Raspberry Pi haha

**Comment by Iapetus-11** [comment]
Someone doesn't know how Discord bots work heh

**Comment by Sh-wayz** [comment]
> Unfortunately, I'm gonna guess that you edited the code under Iapetus11's command since I tested the mechanism and it worked fine (on my bot, on a similar embed).

I legit just downloaded it dude. lemme take a screenshot for ya
![image](https://user-images.githubusercontent.com/67710582/115904639-0212b580-a433-11eb-9c76-d0ce93a1f620.png)
only thing I changed was the config.json
![image](https://user-images.githubusercontent.com/67710582/115904755-2a9aaf80-a433-11eb-8814-8d036d1f760b.png)

**Comment by thunder-red-star** [comment]
Let me guess: You used your eval command to find a server where my alts were auto-mining, then you invited.

That would take a long time searching through 20k guilds and hundreds of thousands of members am I wrong?

**Comment by Sh-wayz** [comment]
Are you responding to me or iapetus?

**Comment by thunder-red-star** [comment]
Petus of course

**Comment by thunder-red-star** [comment]
Also Iapetus I'm making a copy of your bot anyway in Discord.js so really doesn't matter anymore

**Comment by Iapetus-11** [comment]
> Also Iapetus I'm making a copy of your bot anyway in Discord.js so really doesn't matter anymore

Nice have fun



> Let me guess: You used your eval command to find a server where my alts were auto-mining, then you invited.
> 
> That would take a long time searching through 20k guilds and hundreds of thousands of members am I wrong?

No lmao, "autominer#something" triggered an error due to lag and showed up in the error log lmfao

**Comment by Sh-wayz** [comment]
Anyways you should go argue somewhere else this issue is supposed to be about the code problems not you guys' problems.

**Comment by thunder-red-star** [comment]
xD

So I ddosed your bot haha

**Comment by Iapetus-11** [comment]
No?

**Comment by thunder-red-star** [comment]
> Anyways you should go argue somewhere else this issue is supposed to be about the code problems not you guys' problems.

No I have some people to show this to and the link to this thing is in my status

**Comment by thunder-red-star** [comment]
> No?

You just need to see how many times your bot stopped responding to my bot's messages, are you gonna say you stopped it every time?

**Comment by Iapetus-11** [comment]
> > No?
> 
> You just need to see how many times your bot stopped responding to my bot's messages, are you gonna say you stopped it every time?

?

**Comment by Sh-wayz** [comment]
aight this isnt going anywhere

**Comment by thunder-red-star** [comment]
Go back to the server that you invited yourself into (by pure chance I gave your bot a role that had invite perms, the integration didn't have that permission) and look for yourself.

**Comment by Iapetus-11** [comment]
I'm not quite sure what you're asking?

**Comment by thunder-red-star** [comment]
Use your bot to invite yourself back to the server with my alts

**Comment by thunder-red-star** [comment]
Oh yeah I forgot I added your bot to the auto-ban list on my bot xD

**Comment by Iapetus-11** [comment]
> Use your bot to invite yourself back to the server with my alts

why?

**Comment by thunder-red-star** [comment]
No hard feelings though... you said "Cool" when you joined my server so I get to flex that to others (Don't you say "Cool" once every 600 years? Because that's what I heard)

> > Use your bot to invite yourself back to the server with my alts
> 
> why?

Proof of my point

**Comment by Iapetus-11** [comment]
> Proof of my point

what point?

**Comment by thunder-red-star** [comment]
> xD
> 
> So I ddosed your bot haha

**Comment by Iapetus-11** [comment]
The bot receives and parses (to check for valid commands / triggers) around 20 messages per second on average (at times of high traffic more than 100), two users spamming is a drop in the bucket.

**Comment by thunder-red-star** [comment]
> aight this isnt going anywhere

i'll check again

**Comment by thunder-red-star** [comment]
> The bot receives and parses (to check for valid commands / triggers) around 20 messages per second on average (at times of high traffic more than 100), two users spamming is a drop in the bucket.

Ok

**Comment by thunder-red-star** [comment]
![image](https://user-images.githubusercontent.com/67127399/115908970-d692c980-a438-11eb-985c-49d34d0dc9f5.png)
Works for me... check your node.js version.

**Comment by thunder-red-star** [comment]
@Sh-wayz

**Comment by XeDotCom** [comment]
relating to this, i have some things to say:

never gonna give you up
never gonna let you down 
never gonna run around
and desert you

**Comment by thunder-red-star** [comment]
i added this to my bot's items.json:
```
"annoying_petus_followers": {
        "name": "Annoying Petus Followers",
        "worth": 0.0000001,
        "buyable": 0,
        "cost": 0,
        "sticky": 1
    },
```

**Comment by thunder-red-star** [comment]
and then to database.json:
```
"536986067140608041": {
            "steaming_pile_of_shit": 69420,
            "annoying_petus_followers": 3
        }
```

**Comment by thunder-red-star** [comment]
> ![image](https://user-images.githubusercontent.com/67127399/115908970-d692c980-a438-11eb-985c-49d34d0dc9f5.png)
> Works for me... check your node.js version.

no response after proof... haha

**Comment by Sh-wayz** [comment]
Yeah because I was doing school and didn't look dum

**Comment by Sh-wayz** [comment]
I'll check in a bit

**Comment by Sh-wayz** [comment]
![image](https://user-images.githubusercontent.com/67710582/115928211-c1776400-a453-11eb-956e-f27dba8d3b05.png)
hrmm

**Comment by Sh-wayz** [comment]
Looks like the issue is you using a crotchety old outdated node install.

**Comment by thunder-red-star** [comment]
> ![image](https://user-images.githubusercontent.com/67710582/115928211-c1776400-a453-11eb-956e-f27dba8d3b05.png)
> hrmm

You put "Please solve this problem to continue", not "Please solve this problem to continue: `<insert problem here>`"

so it has nothing to split apart since there are no "`"s and therefore returns undefined.

**Comment by thunder-red-star** [comment]
Why are you expecting an answer when you don't give it a problem? "smh my head" as @Iapetus-11 would say

**Comment by thunder-red-star** [comment]
![image](https://user-images.githubusercontent.com/67127399/115930685-e79f0300-a457-11eb-89d2-029b2d60fcf1.png)

**Comment by thunder-red-star** [comment]
@Sh-wayz

**Comment by thunder-red-star** [comment]
> relating to this, i have some things to say:
> 
> never gonna give you up
> never gonna let you down
> never gonna run around
> and desert you

pinged you on discord regarding this issue

**Comment by quaackk** [comment]
- good luck
- have fun
- i appreciate your effort

**Comment by Sh-wayz** [comment]
lmao

**Comment by thunder-red-star** [comment]
![image](https://user-images.githubusercontent.com/67127399/115939089-f642e580-a46a-11eb-9abf-dd45913bba94.png)
![image](https://user-images.githubusercontent.com/67127399/115939113-107cc380-a46b-11eb-86db-bbb3fc44445f.png)
![image](https://user-images.githubusercontent.com/67127399/115939123-196d9500-a46b-11eb-837d-543f9f32df3b.png)

**Comment by Sh-wayz** [comment]
Yeah it works in node but I legit changed nothing about your code and it crashed for some reason

**Comment by Sh-wayz** [comment]
idk

**Comment by thunder-red-star** [comment]
> lmao

i made a fix to the miner but NOT FOR YOUR ISSUE SINCE YOU ARE SCAMMING ME

**Comment by Sh-wayz** [comment]
bro what

**Comment by thunder-red-star** [comment]
i had someone else test it, it works fine
they shared their screen it works perfect

**Comment by thunder-red-star** [comment]
please don't make me bring another alt online so i can show you

**Comment by Sh-wayz** [comment]
So? I'm not saying it doesn't always work dude just saying that it didn't when I tried. just thought you might want a heads up was all

**Comment by thunder-red-star** [comment]
ok

**Comment by thunder-red-star** [comment]
use the "try on replit" button, test it there

if you don't have the hacker plan (in that case smh my head) replace the config.token with process.env.token and then put the token into the environment button (i'm assuming you know how to do that)

**Comment by thunder-red-star** [comment]
whoops
